//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Contacts.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_CONTACTS_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_INSERT_DIALOG               129
#define IDD_QUERY_DIALOG                130
#define IDD_LOGIN_DIALOG                132
#define IDR_CONTACTS_MENU               133
#define IDR_LIST_RCLICK_MENU            134
#define IDR_POPUP_MENU                  134
#define IDB_CLEAR_PHOTO                 138
#define IDD_UPDATE_GROUP_DIALOG         139
#define IDD_GROUP_DIALOG                139
#define IDD_USER_DIALOG                 141
#define IDD_GROUP_ADD_DIALOG            142
#define IDC_EDIT1                       1000
#define IDC_USERNAME                    1000
#define IDC_INPUT_BOX                   1000
#define IDC_QUICK_SEARCH                1000
#define IDC_ADDRESS                     1000
#define IDC_GROUP_NEW_NAME              1000
#define IDC_QUERY_FILTER                1000
#define IDC_GROUP_NAMEBOX               1000
#define IDC_GROUP_NAME                  1000
#define IDC_CONTACTS_LIST               1001
#define IDC_PASSWORD                    1001
#define IDC_INSERT                      1002
#define IDC_RECORD_INSERT               1002
#define IDC_DELDETE                     1003
#define IDC_F_EMAIL                     1003
#define IDC_RECORD_DELETE               1003
#define IDC_QUREY                       1004
#define IDC_RECORD_QUERY                1004
#define IDC_MODIFY                      1005
#define IDC_RECORD_MODIFY               1005
#define IDC_F_SEX                       1005
#define IDC_F_BLOODTYPE                 1006
#define IDC_INSERT_EXEC                 1015
#define IDC_QUERY_LIST                  1018
#define IDC_RECORD_LIST                 1019
#define IDC_F_NAME                      1031
#define IDC_F_MOBILEPHONE               1032
#define IDC_F_TELEPHONE                 1033
#define IDC_F_PROVINCE                  1034
#define IDC_F_CITY                      1035
#define IDC_F_UNIVERSITY                1036
#define IDC_F_DEPARTMENT                1037
#define IDC_F_MAJOR                     1038
#define IDC_QUERY_EXEC                  1039
#define IDC_F_BIRTHDATE                 1045
#define IDC_LOGIN                       1046
#define IDC_CANCEL                      1047
#define IDC_TREE1                       1047
#define IDC_SLIDER1                     1051
#define IDC_UPLOAD_PHOTO                1071
#define IDC_PHOTO_PATH                  1072
#define IDC_PHOTO                       1073
#define IDC_CLEAR_PHOTO                 1075
#define IDC_LIST_GROUP                  1076
#define IDC_GROUP_LISTBOX               1076
#define IDC_GROUP_ADD                   1077
#define IDC_GROUP_DEL                   1078
#define IDC_QUERY_METHOD                1078
#define IDC_GROUP_CANCEL                1079
#define IDC_GROUP_RENAME                1080
#define IDC_ABOUT_CANCEL                1082
#define IDC_ABOUT_TXT                   1083
#define IDC_LIST_USER                   1084
#define IDC_ADD_USER                    1085
#define IDC_DEL_USER                    1087
#define IDC_PRE                         1087
#define IDC_MOD_PWD                     1088
#define IDC_NEXT                        1088
#define IDC_FIRST                       1089
#define IDC_LAST                        1090
#define IDC_NAME                        2000
#define IDC_SEX                         2001
#define IDC_BLOODTYPE                   2002
#define IDC_BIRTHDATE                   2003
#define IDC_GROUP                       2004
#define IDC_MOBILEPHONE                 2005
#define IDC_TELEPHONE                   2006
#define IDC_QQ                          2007
#define IDC_EMAIL                       2008
#define IDC_PROVINCE                    2009
#define IDC_CITY                        2010
#define IDC_UNIVERSITY                  2011
#define IDC_DEPARTMENT                  2012
#define IDC_MAJOR                       2013
#define IDC_GRADE                       2014
#define ID_MENUITEM32771                32771
#define ID_MENU_NEW_RECORD              32771
#define ID_MENUITEM32772                32772
#define ID_MENU_MODIFY                  32772
#define ID_MENUITEM32773                32773
#define ID_MENUITEM32774                32774
#define ID_MENU_QUERY                   32774
#define ID_MENUITEM32775                32775
#define ID_MENU_EXIT                    32775
#define ID_MENUITEM32777                32777
#define ID_MENUITEM32778                32778
#define ID_MENUITEM32779                32779
#define ID_MENUITEM32780                32780
#define ID_MENUITEM32781                32781
#define ID_MENU_PREFERENCE              32781
#define ID_MENU_NEW_GROUP               32782
#define ID_MENU_ABOUT                   32783
#define ID_MENU_HELP                    32784
#define ID_MENU_DELETE                  32785
#define ID_MENUITEM32787                32787
#define ID_MENU_REFRESH                 32788
#define ID_MENU_IMPORT                  32789
#define ID_MENU_EXPORT                  32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
